FROM ubuntu:14.04

RUN apt-get update && apt-get install -y velvet

# from source
#RUN apt-get update && apt-get install -y git build-essential
#RUN git clone git://github.com/dzerbino/velvet.git && \
#	cd velvet && \
#	make 'MAXKMERLENGTH=69' && \
#	cp velvetg /usr/local/bin/ && \
#	cp velveth /usr/local/bin/ && \
#	cd .. \
#	rm -rf velvet
