# diamond

FROM ubuntu:14.04
#RUN apt-get update

ADD http://www-ab.informatik.uni-tuebingen.de/data/software/diamond/download/public/diamond-bin-0.5.2.tar.gz /diamond/
RUN cd /diamond/ && tar -xzvf diamond-bin-0.5.2.tar.gz ; ln -s /diamond/bin/diamond /usr/local/bin/

